language: objective-c
osx_image: xcode8.1
branches:
  only:
    - master
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - WORKSPACE=WebViewController.xcworkspace
  - IOS_FRAMEWORK_SCHEME="WebViewController"
  - EXAMPLE_SCHEME="Example"
  - DESTINATION='platform=iOS Simulator,name=iPhone 6S'
script:
  - xcodebuild clean -workspace "$WORKSPACE" -scheme "$IOS_FRAMEWORK_SCHEME" -destination "$DESTINATION" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO | xcpretty
